#ifndef _MBR_PARTITION_TYPE
#define _MBR_PARTITION_TYPE

#define MBR_EXTENDED_05_PARTITION				0x05
#define MBR_exFAT_PARTITION						0x07
#define MBR_NTFS_PARTITION						0x07
#define MBR_FAT32_PARTITION						0x0B
#define MBR_EXTENDED_0F_PARTITION				0x0F

#endif // _MBR_PARTITION_TYPE