#ifndef _FONT_H
#define _FONT_H

#include <stdint.h>

enum {
	MonospaceFont,			// Моноширинный шрифт
	ProportionalFont		// Пропорциональный шрифт
};

typedef struct {
	//uint8_t type;			// {MonospaceFont, ProportionalFont}
	uint8_t offset;
	uint8_t width;
	uint8_t height;
	uint8_t *chars;
} Font;

#define ________				0x00
#define X_______				0x01
#define _X______				0x02
#define XX______				0x03
#define __X_____				0x04
#define X_X_____				0x05
#define _XX_____				0x06
#define XXX_____				0x07
#define ___X____				0x08
#define X__X____				0x09
#define _X_X____				0x0A
#define XX_X____				0x0B
#define __XX____				0x0C
#define X_XX____				0x0D
#define _XXX____				0x0E
#define XXXX____				0x0F
#define ____X___				0x10
#define X___X___				0x11
#define _X__X___				0x12
#define XX__X___				0x13
#define __X_X___				0x14
#define X_X_X___				0x15
#define _XX_X___				0x16
#define XXX_X___				0x17
#define ___XX___				0x18
#define X__XX___				0x19
#define _X_XX___				0x1A
#define XX_XX___				0x1B
#define __XXX___				0x1C
#define X_XXX___				0x1D
#define _XXXX___				0x1E
#define XXXXX___				0x1F
#define _____X__				0x20
#define X____X__				0x21
#define _X___X__				0x22
#define XX___X__				0x23
#define __X__X__				0x24
#define X_X__X__				0x25
#define _XX__X__				0x26
#define XXX__X__				0x27
#define ___X_X__				0x28
#define X__X_X__				0x29
#define _X_X_X__				0x2A
#define XX_X_X__				0x2B
#define __XX_X__				0x2C
#define X_XX_X__				0x2D
#define _XXX_X__				0x2E
#define XXXX_X__				0x2F
#define ____XX__				0x30
#define X___XX__				0x31
#define _X__XX__				0x32
#define XX__XX__				0x33
#define __X_XX__				0x34
#define X_X_XX__				0x35
#define _XX_XX__				0x36
#define XXX_XX__				0x37
#define ___XXX__				0x38
#define X__XXX__				0x39
#define _X_XXX__				0x3A
#define XX_XXX__				0x3B
#define __XXXX__				0x3C
#define X_XXXX__				0x3D
#define _XXXXX__				0x3E
#define XXXXXX__				0x3F
#define ______X_				0x40
#define X_____X_				0x41
#define _X____X_				0x42
#define XX____X_				0x43
#define __X___X_				0x44
#define X_X___X_				0x45
#define _XX___X_				0x46
#define XXX___X_				0x47
#define ___X__X_				0x48
#define X__X__X_				0x49
#define _X_X__X_				0x4A
#define XX_X__X_				0x4B
#define __XX__X_				0x4C
#define X_XX__X_				0x4D
#define _XXX__X_				0x4E
#define XXXX__X_				0x4F
#define ____X_X_				0x50
#define X___X_X_				0x51
#define _X__X_X_				0x52
#define XX__X_X_				0x53
#define __X_X_X_				0x54
#define X_X_X_X_				0x55
#define _XX_X_X_				0x56
#define XXX_X_X_				0x57
#define ___XX_X_				0x58
#define X__XX_X_				0x59
#define _X_XX_X_				0x5A
#define XX_XX_X_				0x5B
#define __XXX_X_				0x5C
#define X_XXX_X_				0x5D
#define _XXXX_X_				0x5E
#define XXXXX_X_				0x5F
#define _____XX_				0x60
#define X____XX_				0x61
#define _X___XX_				0x62
#define XX___XX_				0x63
#define __X__XX_				0x64
#define X_X__XX_				0x65
#define _XX__XX_				0x66
#define XXX__XX_				0x67
#define ___X_XX_				0x68
#define X__X_XX_				0x69
#define _X_X_XX_				0x6A
#define XX_X_XX_				0x6B
#define __XX_XX_				0x6C
#define X_XX_XX_				0x6D
#define _XXX_XX_				0x6E
#define XXXX_XX_				0x6F
#define ____XXX_				0x70
#define X___XXX_				0x71
#define _X__XXX_				0x72
#define XX__XXX_				0x73
#define __X_XXX_				0x74
#define X_X_XXX_				0x75
#define _XX_XXX_				0x76
#define XXX_XXX_				0x77
#define ___XXXX_				0x78
#define X__XXXX_				0x79
#define _X_XXXX_				0x7A
#define XX_XXXX_				0x7B
#define __XXXXX_				0x7C
#define X_XXXXX_				0x7D
#define _XXXXXX_				0x7E
#define XXXXXXX_				0x7F
#define _______X				0x80
#define X______X				0x81
#define _X_____X				0x82
#define XX_____X				0x83
#define __X____X				0x84
#define X_X____X				0x85
#define _XX____X				0x86
#define XXX____X				0x87
#define ___X___X				0x88
#define X__X___X				0x89
#define _X_X___X				0x8A
#define XX_X___X				0x8B
#define __XX___X				0x8C
#define X_XX___X				0x8D
#define _XXX___X				0x8E
#define XXXX___X				0x8F
#define ____X__X				0x90
#define X___X__X				0x91
#define _X__X__X				0x92
#define XX__X__X				0x93
#define __X_X__X				0x94
#define X_X_X__X				0x95
#define _XX_X__X				0x96
#define XXX_X__X				0x97
#define ___XX__X				0x98
#define X__XX__X				0x99
#define _X_XX__X				0x9A
#define XX_XX__X				0x9B
#define __XXX__X				0x9C
#define X_XXX__X				0x9D
#define _XXXX__X				0x9E
#define XXXXX__X				0x9F
#define _____X_X				0xA0
#define X____X_X				0xA1
#define _X___X_X				0xA2
#define XX___X_X				0xA3
#define __X__X_X				0xA4
#define X_X__X_X				0xA5
#define _XX__X_X				0xA6
#define XXX__X_X				0xA7
#define ___X_X_X				0xA8
#define X__X_X_X				0xA9
#define _X_X_X_X				0xAA
#define XX_X_X_X				0xAB
#define __XX_X_X				0xAC
#define X_XX_X_X				0xAD
#define _XXX_X_X				0xAE
#define XXXX_X_X				0xAF
#define ____XX_X				0xB0
#define X___XX_X				0xB1
#define _X__XX_X				0xB2
#define XX__XX_X				0xB3
#define __X_XX_X				0xB4
#define X_X_XX_X				0xB5
#define _XX_XX_X				0xB6
#define XXX_XX_X				0xB7
#define ___XXX_X				0xB8
#define X__XXX_X				0xB9
#define _X_XXX_X				0xBA
#define XX_XXX_X				0xBB
#define __XXXX_X				0xBC
#define X_XXXX_X				0xBD
#define _XXXXX_X				0xBE
#define XXXXXX_X				0xBF
#define ______XX				0xC0
#define X_____XX				0xC1
#define _X____XX				0xC2
#define XX____XX				0xC3
#define __X___XX				0xC4
#define X_X___XX				0xC5
#define _XX___XX				0xC6
#define XXX___XX				0xC7
#define ___X__XX				0xC8
#define X__X__XX				0xC9
#define _X_X__XX				0xCA
#define XX_X__XX				0xCB
#define __XX__XX				0xCC
#define X_XX__XX				0xCD
#define _XXX__XX				0xCE
#define XXXX__XX				0xCF
#define ____X_XX				0xD0
#define X___X_XX				0xD1
#define _X__X_XX				0xD2
#define XX__X_XX				0xD3
#define __X_X_XX				0xD4
#define X_X_X_XX				0xD5
#define _XX_X_XX				0xD6
#define XXX_X_XX				0xD7
#define ___XX_XX				0xD8
#define X__XX_XX				0xD9
#define _X_XX_XX				0xDA
#define XX_XX_XX				0xDB
#define __XXX_XX				0xDC
#define X_XXX_XX				0xDD
#define _XXXX_XX				0xDE
#define XXXXX_XX				0xDF
#define _____XXX				0xE0
#define X____XXX				0xE1
#define _X___XXX				0xE2
#define XX___XXX				0xE3
#define __X__XXX				0xE4
#define X_X__XXX				0xE5
#define _XX__XXX				0xE6
#define XXX__XXX				0xE7
#define ___X_XXX				0xE8
#define X__X_XXX				0xE9
#define _X_X_XXX				0xEA
#define XX_X_XXX				0xEB
#define __XX_XXX				0xEC
#define X_XX_XXX				0xED
#define _XXX_XXX				0xEE
#define XXXX_XXX				0xEF
#define ____XXXX				0xF0
#define X___XXXX				0xF1
#define _X__XXXX				0xF2
#define XX__XXXX				0xF3
#define __X_XXXX				0xF4
#define X_X_XXXX				0xF5
#define _XX_XXXX				0xF6
#define XXX_XXXX				0xF7
#define ___XXXXX				0xF8
#define X__XXXXX				0xF9
#define _X_XXXXX				0xFA
#define XX_XXXXX				0xFB
#define __XXXXXX				0xFC
#define X_XXXXXX				0xFD
#define _XXXXXXX				0xFE
#define XXXXXXXX				0xFF

#endif // _FONT_H
